baseURL = 'https://www.smarx.com.br/'
languageCode = 'pt-BR'
title = 'Blog'

theme = 'lugo'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true
